# Generated by Django 3.2.5 on 2021-08-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_pkm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('passive_name', models.CharField(max_length=30)),
                ('passive_img', models.CharField(max_length=150)),
                ('passive_effect', models.TextField()),
                ('attack_name', models.CharField(max_length=30)),
                ('attack_effect', models.TextField()),
            ],
        ),
    ]
