# Generated by Django 3.2.5 on 2021-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_pokemon_passive_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='passive_img',
            field=models.CharField(max_length=50),
        ),
    ]
