# Generated by Django 3.2.5 on 2021-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_auto_20210830_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effect_description',
            field=models.CharField(max_length=10),
        ),
    ]
