# Generated by Django 3.2.7 on 2021-09-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0027_auto_20210908_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='detail_img',
            field=models.CharField(default='', max_length=50),
        ),
    ]
