# Generated by Django 3.2.5 on 2021-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0032_pkm_item_pokemon item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pkm_battle_item',
            constraint=models.UniqueConstraint(fields=('pkm_id', 'battle_item_id'), name='pokemon battle item'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('pkm_id', 'name'), name='pokemon skill'),
        ),
    ]
