# Generated by Django 3.2.7 on 2021-09-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0033_auto_20210920_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='en_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='en_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
