# Generated by Django 3.2.7 on 2021-09-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0037_rename_type_pokemon_type_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='en_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='en_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='damage_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
