# Generated by Django 3.2.7 on 2021-09-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0038_auto_20210922_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle_item',
            old_name='name',
            new_name='name_text',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='name_text',
        ),
    ]
