# Generated by Django 3.2.7 on 2021-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0045_rename_type_skill_type_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
