# Generated by Django 3.2.7 on 2021-09-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0048_pokemon_passive_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='type_text',
        ),
    ]
