# Generated by Django 3.2.7 on 2021-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0054_item_status_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='count',
            field=models.BigIntegerField(),
        ),
    ]
