# Generated by Django 3.2.7 on 2021-09-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0058_auto_20210928_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pkm_item_test',
        ),
    ]
