# Generated by Django 3.2.7 on 2021-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0066_rename_email_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_upgrade_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
