# Generated by Django 3.2.5 on 2021-08-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_test_pkm_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_pkm',
            name='img',
            field=models.CharField(max_length=150),
        ),
    ]
