# Generated by Django 3.2.5 on 2021-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_test_pkm_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_pkm',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
