# Generated by Django 3.2.5 on 2021-08-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_test_pkm_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_pkm',
        ),
    ]
