# Generated by Django 3.2.5 on 2021-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0006_delete_test_pkm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('img', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=8)),
                ('passive_name', models.CharField(max_length=20)),
                ('passive_effect', models.TextField()),
                ('attack_effect', models.TextField()),
                ('offense', models.IntegerField()),
                ('endurance', models.IntegerField()),
                ('mobility', models.IntegerField()),
                ('scoring', models.IntegerField()),
                ('support', models.IntegerField()),
                ('level', models.IntegerField()),
                ('before_id', models.BigIntegerField()),
            ],
        ),
    ]
