# Generated by Django 3.2.5 on 2021-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='before_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
