# Generated by Django 3.2.5 on 2021-08-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20210824_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('effect', models.TextField()),
                ('cooltime', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('effect', models.TextField()),
                ('status_1', models.CharField(max_length=50)),
                ('status_2', models.CharField(max_length=50)),
                ('status_3', models.CharField(max_length=50)),
                ('effect_1', models.TextField()),
                ('effect_2', models.TextField()),
                ('effect_3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooltime', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('count', models.BigIntegerField()),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Pkm_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.item')),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Pkm_ballte_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('battle_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.battle_item')),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
    ]
