# Generated by Django 3.2.5 on 2021-08-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_battle_item_item_pkm_ballte_item_pkm_item_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='passive_img',
            field=models.CharField(default='', max_length=50),
        ),
    ]
