# Generated by Django 3.2.5 on 2021-08-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_skill_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='effect',
            new_name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='effect_description',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect_1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect_2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='effect_3',
            field=models.CharField(max_length=10),
        ),
    ]
