# Generated by Django 3.2.5 on 2021-08-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0017_auto_20210830_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default='', max_length=50),
        ),
    ]
