# Generated by Django 3.2.5 on 2021-08-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0018_item_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pkm_ballte_item',
            new_name='Pkm_battle_item',
        ),
    ]
