# Generated by Django 3.2.5 on 2021-09-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0019_rename_pkm_ballte_item_pkm_battle_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='before_id',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='level',
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
    ]
