# Generated by Django 3.2.5 on 2021-09-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0020_auto_20210901_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
