# Generated by Django 3.2.5 on 2021-09-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0021_evolution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='before_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
