# Generated by Django 3.2.5 on 2021-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0023_auto_20210902_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
