# Generated by Django 3.2.5 on 2021-09-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0024_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
    ]
