# Generated by Django 3.2.5 on 2021-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0025_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='difficulty',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='type2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='type3',
            field=models.CharField(default='', max_length=10),
        ),
    ]
