# Generated by Django 3.2.5 on 2021-09-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0026_auto_20210908_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type3',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='difficulty',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type3',
            field=models.CharField(default='', max_length=10),
        ),
    ]
