# Generated by Django 3.2.5 on 2021-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0030_auto_20210918_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_10',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_11',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_12',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_13',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_14',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_15',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_16',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_17',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_18',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_19',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_2',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_20',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_21',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_22',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_23',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_24',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_25',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_26',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_27',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_28',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_29',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_3',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_30',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_4',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_5',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_6',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_7',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_8',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='status_9',
            field=models.CharField(default='', max_length=40),
        ),
    ]
