# Generated by Django 3.2.7 on 2021-09-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0034_auto_20210920_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='attack_type',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='type3',
            new_name='damage_type_text',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='name_text',
        ),
    ]
