# Generated by Django 3.2.7 on 2021-09-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0036_rename_type2_pokemon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='type_text',
        ),
    ]
