# Generated by Django 3.2.7 on 2021-09-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0039_auto_20210922_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='name',
            new_name='name_text',
        ),
    ]
