# Generated by Django 3.2.7 on 2021-09-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0040_rename_name_evolution_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle_item',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='evolution',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
