# Generated by Django 3.2.7 on 2021-09-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0041_auto_20210922_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='attack_type_text',
            field=models.CharField(default='', max_length=8),
        ),
    ]
