# Generated by Django 3.2.7 on 2021-09-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0042_pokemon_attack_type_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='name_text',
        ),
    ]
