# Generated by Django 3.2.7 on 2021-09-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0044_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='type',
            new_name='type_text',
        ),
    ]
