# Generated by Django 3.2.7 on 2021-09-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0046_skill_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='passive_name',
            new_name='passive_name_text',
        ),
    ]
