# Generated by Django 3.2.7 on 2021-09-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0047_rename_passive_name_pokemon_passive_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='passive_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
