# Generated by Django 3.2.7 on 2021-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0049_rename_type_item_type_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
