# Generated by Django 3.2.7 on 2021-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0050_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
