# Generated by Django 3.2.7 on 2021-09-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0051_alter_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contents',
            new_name='url',
        ),
    ]
