# Generated by Django 3.2.7 on 2021-09-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0053_pokemon_pokemon_pok_name_te_ffa9e6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_increase',
            field=models.CharField(default='', max_length=30),
        ),
    ]
