# Generated by Django 3.2.7 on 2021-09-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0057_pokemon_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pkm_item_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('item_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_1', to='pokemon.item')),
                ('item_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_2', to='pokemon.item')),
                ('item_id_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_3', to='pokemon.item')),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pkm_item_test',
            constraint=models.UniqueConstraint(fields=('pkm_id', 'item_id_1', 'item_id_2', 'item_id_3'), name='pokemon item test'),
        ),
    ]
