# Generated by Django 3.2.7 on 2021-10-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0059_delete_pkm_item_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_1', to='pokemon.item')),
                ('item_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_2', to='pokemon.item')),
                ('item_id_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id_3', to='pokemon.item')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill_build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_id_1', to='pokemon.skill')),
                ('skill_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_id_2', to='pokemon.skill')),
                ('skill_id_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_id_3', to='pokemon.skill')),
                ('skill_id_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_id_4', to='pokemon.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Old_build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('battle_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.battle_item')),
                ('item_build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.item_build')),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('skill_build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.skill_build')),
                ('update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.update')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('battle_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.battle_item')),
                ('item_build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.item_build')),
                ('pkm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('skill_build_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.skill_build')),
                ('update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.update')),
            ],
        ),
    ]
