# Generated by Django 3.2.7 on 2021-10-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0060_build_item_build_old_build_skill_build_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='old_build',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
    ]
