# Generated by Django 3.2.7 on 2021-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0061_auto_20211001_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='old_build',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
