# Generated by Django 3.2.7 on 2021-10-01 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0063_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 16, 57, 22, 67091, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
