# Generated by Django 3.2.7 on 2021-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0064_auto_20211002_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
