# Generated by Django 3.2.7 on 2021-10-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0065_alter_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='name',
        ),
    ]
