# Generated by Django 3.2.7 on 2021-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0067_item_upgrade_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='position',
            field=models.CharField(default='', max_length=10),
        ),
    ]
