# Generated by Django 3.2.7 on 2021-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0068_build_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='build',
            constraint=models.UniqueConstraint(fields=('pkm_id', 'item_build_id', 'skill_build_id', 'battle_item_id', 'position'), name='pokemon build'),
        ),
        migrations.AddConstraint(
            model_name='item_build',
            constraint=models.UniqueConstraint(fields=('item_id_1', 'item_id_2', 'item_id_3'), name='pokemon build item'),
        ),
        migrations.AddConstraint(
            model_name='skill_build',
            constraint=models.UniqueConstraint(fields=('skill_id_1', 'skill_id_2', 'skill_id_3', 'skill_id_4'), name='pokemon build skill'),
        ),
    ]
